# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapMainWindow(object):
	def setupUi(self, MapMainWindow):
		MapMainWindow.setObjectName("MapMainWindow")
		MapMainWindow.resize(600, 800)
		self.centralwidget = QtWidgets.QWidget(MapMainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setObjectName("verticalLayout")
		self.localArea = QtWidgets.QWidget(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.localArea.sizePolicy().hasHeightForWidth())
		self.localArea.setSizePolicy(sizePolicy)
		self.localArea.setObjectName("localArea")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.localArea)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.countryLabel = QtWidgets.QLabel(self.localArea)
		self.countryLabel.setObjectName("countryLabel")
		self.horizontalLayout_2.addWidget(self.countryLabel)
		self.cityLabel = QtWidgets.QLabel(self.localArea)
		self.cityLabel.setObjectName("cityLabel")
		self.horizontalLayout_2.addWidget(self.cityLabel)
		self.latitudeLabel = QtWidgets.QLabel(self.localArea)
		self.latitudeLabel.setObjectName("latitudeLabel")
		self.horizontalLayout_2.addWidget(self.latitudeLabel)
		self.longitudeLabel = QtWidgets.QLabel(self.localArea)
		self.longitudeLabel.setObjectName("longitudeLabel")
		self.horizontalLayout_2.addWidget(self.longitudeLabel)
		self.verticalLayout.addWidget(self.localArea)
		self.displayArea = QtWidgets.QWidget(self.centralwidget)
		self.displayArea.setObjectName("displayArea")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.displayArea)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.verticalLayout.addWidget(self.displayArea)
		self.inputArea = QtWidgets.QWidget(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.inputArea.sizePolicy().hasHeightForWidth())
		self.inputArea.setSizePolicy(sizePolicy)
		self.inputArea.setObjectName("inputArea")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.inputArea)
		self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.routeArea = QtWidgets.QWidget(self.inputArea)
		self.routeArea.setObjectName("routeArea")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.routeArea)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.routeInput = QtWidgets.QGridLayout()
		self.routeInput.setObjectName("routeInput")
		self.route0 = QtWidgets.QPushButton(self.routeArea)
		self.route0.setObjectName("route0")
		self.routeInput.addWidget(self.route0, 0, 0, 1, 1)
		self.route4 = QtWidgets.QPushButton(self.routeArea)
		self.route4.setObjectName("route4")
		self.routeInput.addWidget(self.route4, 0, 4, 1, 1)
		self.route1 = QtWidgets.QPushButton(self.routeArea)
		self.route1.setObjectName("route1")
		self.routeInput.addWidget(self.route1, 0, 1, 1, 1)
		self.route3 = QtWidgets.QPushButton(self.routeArea)
		self.route3.setObjectName("route3")
		self.routeInput.addWidget(self.route3, 0, 3, 1, 1)
		self.route2 = QtWidgets.QPushButton(self.routeArea)
		self.route2.setObjectName("route2")
		self.routeInput.addWidget(self.route2, 0, 2, 1, 1)
		self.route5 = QtWidgets.QPushButton(self.routeArea)
		self.route5.setObjectName("route5")
		self.routeInput.addWidget(self.route5, 1, 0, 1, 1)
		self.route6 = QtWidgets.QPushButton(self.routeArea)
		self.route6.setObjectName("route6")
		self.routeInput.addWidget(self.route6, 1, 1, 1, 1)
		self.route7 = QtWidgets.QPushButton(self.routeArea)
		self.route7.setObjectName("route7")
		self.routeInput.addWidget(self.route7, 1, 2, 1, 1)
		self.route8 = QtWidgets.QPushButton(self.routeArea)
		self.route8.setObjectName("route8")
		self.routeInput.addWidget(self.route8, 1, 3, 1, 1)
		self.allroute = QtWidgets.QPushButton(self.routeArea)
		self.allroute.setObjectName("allroute")
		self.routeInput.addWidget(self.allroute, 1, 4, 1, 1)
		self.verticalLayout_7.addLayout(self.routeInput)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.cfmRouteBtn = QtWidgets.QPushButton(self.routeArea)
		self.cfmRouteBtn.setObjectName("cfmRouteBtn")
		self.horizontalLayout.addWidget(self.cfmRouteBtn)
		self.cclRouteBtn = QtWidgets.QPushButton(self.routeArea)
		self.cclRouteBtn.setObjectName("cclRouteBtn")
		self.horizontalLayout.addWidget(self.cclRouteBtn)
		self.verticalLayout_7.addLayout(self.horizontalLayout)
		self.verticalLayout_3.addWidget(self.routeArea)
		self.backArea = QtWidgets.QWidget(self.inputArea)
		self.backArea.setObjectName("backArea")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.backArea)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		spacerItem1 = QtWidgets.QSpacerItem(480, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem1)
		self.backBtn = QtWidgets.QPushButton(self.backArea)
		self.backBtn.setObjectName("backBtn")
		self.horizontalLayout_4.addWidget(self.backBtn)
		self.verticalLayout_3.addWidget(self.backArea)
		self.placeArea = QtWidgets.QWidget(self.inputArea)
		self.placeArea.setObjectName("placeArea")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.placeArea)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.placeInput = QtWidgets.QFormLayout()
		self.placeInput.setObjectName("placeInput")
		self.label_2 = QtWidgets.QLabel(self.placeArea)
		self.label_2.setObjectName("label_2")
		self.placeInput.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
		self.originInput = QtWidgets.QLineEdit(self.placeArea)
		self.originInput.setObjectName("originInput")
		self.placeInput.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originInput)
		self.label_3 = QtWidgets.QLabel(self.placeArea)
		self.label_3.setObjectName("label_3")
		self.placeInput.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
		self.destInput = QtWidgets.QLineEdit(self.placeArea)
		self.destInput.setObjectName("destInput")
		self.placeInput.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.destInput)
		self.verticalLayout_6.addLayout(self.placeInput)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem2)
		self.cfmPlaceBtn = QtWidgets.QPushButton(self.placeArea)
		self.cfmPlaceBtn.setObjectName("cfmPlaceBtn")
		self.horizontalLayout_3.addWidget(self.cfmPlaceBtn)
		self.clrPlaceBtn = QtWidgets.QPushButton(self.placeArea)
		self.clrPlaceBtn.setObjectName("clrPlaceBtn")
		self.horizontalLayout_3.addWidget(self.clrPlaceBtn)
		self.verticalLayout_6.addLayout(self.horizontalLayout_3)
		self.verticalLayout_3.addWidget(self.placeArea)
		self.verticalLayout.addWidget(self.inputArea)
		MapMainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MapMainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 23))
		self.menubar.setObjectName("menubar")
		self.menu_Menu = QtWidgets.QMenu(self.menubar)
		self.menu_Menu.setObjectName("menu_Menu")
		MapMainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MapMainWindow)
		self.statusbar.setObjectName("statusbar")
		MapMainWindow.setStatusBar(self.statusbar)
		self.menubar.addAction(self.menu_Menu.menuAction())

		self.retranslateUi(MapMainWindow)
		self.clrPlaceBtn.clicked.connect(self.originInput.clear)
		self.clrPlaceBtn.clicked.connect(self.destInput.clear)
		QtCore.QMetaObject.connectSlotsByName(MapMainWindow)

	def retranslateUi(self, MapMainWindow):
		_translate = QtCore.QCoreApplication.translate
		MapMainWindow.setWindowTitle(_translate("MapMainWindow", "MainWindow"))
		self.countryLabel.setText(_translate("MapMainWindow", "Country:"))
		self.cityLabel.setText(_translate("MapMainWindow", "City:"))
		self.latitudeLabel.setText(_translate("MapMainWindow", "Latitude:"))
		self.longitudeLabel.setText(_translate("MapMainWindow", "Longitude:"))
		self.route0.setText(_translate("MapMainWindow", "Route1"))
		self.route4.setText(_translate("MapMainWindow", "Route5"))
		self.route1.setText(_translate("MapMainWindow", "Route2"))
		self.route3.setText(_translate("MapMainWindow", "Route4"))
		self.route2.setText(_translate("MapMainWindow", "Route3"))
		self.route5.setText(_translate("MapMainWindow", "Route6"))
		self.route6.setText(_translate("MapMainWindow", "Route7"))
		self.route7.setText(_translate("MapMainWindow", "Route8"))
		self.route8.setText(_translate("MapMainWindow", "Route9"))
		self.allroute.setText(_translate("MapMainWindow", "AllRoute"))
		self.cfmRouteBtn.setText(_translate("MapMainWindow", "&Confirm"))
		self.cclRouteBtn.setText(_translate("MapMainWindow", "&Cancel"))
		self.backBtn.setText(_translate("MapMainWindow", "&Back"))
		self.label_2.setText(_translate("MapMainWindow", "Origin:"))
		self.label_3.setText(_translate("MapMainWindow", "Destination:"))
		self.cfmPlaceBtn.setText(_translate("MapMainWindow", "&Confirm"))
		self.clrPlaceBtn.setText(_translate("MapMainWindow", "&Clear"))
		self.menu_Menu.setTitle(_translate("MapMainWindow", "&Menu"))

